name: Deploy Hexo to GitHub Pages

# 监听 main 分支的推送操作
on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            # 检出 hexo 分支的 Hexo 环境
            - name: Checkout hexo branch
              uses: actions/checkout@v3
              with:
                  ref: hexo # 指定为 hexo 分支
                  path: blog

            # 设置 sparse-checkout 只检出 Blog 文件夹
            - name: Get Blog Files
              uses: actions/checkout@v3
              with:
                  ref: main # 从 main 分支获取文章
                  path: blog/source/_posts # 将文章内容放在 Hexo 项目的 source 文件夹
                  sparse-checkout: true # 启用稀疏检出
                  fetch-depth: 0 # 获取完整的历史记录，以确保可以正确检出
              run: |
                  git sparse-checkout init --cone  # 初始化 sparse-checkout
                  echo "Blog/*" >> .git/info/sparse-checkout  # 设置稀疏检出的路径
                  git sparse-checkout reapply  # 重新应用 sparse-checkout 配置
                  git pull origin main  # 拉取 main 分支中指定的内容

            # 设置 Node.js 环境
            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                  node-version: "16" # 选择 Node.js 版本

            # 缓存 Node.js 依赖
            - name: Cache dependencies
              uses: actions/cache@v3
              with:
                  path: node_modules
                  key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-node-

            # 安装项目依赖
            - name: Install dependencies
              run: npm install
              working-directory: ./blog

            # 安装 Hexo CLI
            - name: Install Hexo CLI
              run: npm install -g hexo-cli
              working-directory: ./blog

            # 生成静态页面
            - name: Generate static pages
              run: hexo generate
              working-directory: ./blog

            # 将生成的静态页面发布到 GitHub Pages
            - name: Deploy to GitHub Pages
              uses: peaceiris/actions-gh-pages@v3
              with:
                  personal_token: ${{ secrets.PERSONAL_TOKEN }} # 使用 GitHub 密钥
                  publish_dir: ./blog/public # Hexo 生成的静态文件目录
                  external_repository: ZeroHzzzz/ZeroHzzzz.github.io # 替换为目标 GitHub Pages 仓库
                  publish_branch: main # 或 main，指定发布的分支
